<?xml version="1.0" encoding="utf-8"?><Database Name="cvb815a_assign2" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=135.23.74.62;Initial Catalog=cvb815a_assign2;Persist Security Info=True;User ID=programaccess" SettingsObjectName="Assignment_2.My.MySettings" SettingsPropertyName="cvb815a_assign2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="province" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="postal_code" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Address_Order" Member="Orders" ThisKey="id" OtherKey="shipping_address_id" Type="Order" />
      <Association Name="Customer_Address" Member="Customer" ThisKey="customer_id" OtherKey="id" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="inventory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Product_Order_Line" Member="Order_Lines" ThisKey="id" OtherKey="product_id" Type="Order_Line" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="credit_limit" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Address" Member="Addresses" ThisKey="id" OtherKey="customer_id" Type="Address" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="id" OtherKey="customer_id" Type="Order" />
      <Association Name="ExpandedOrders_Customer" Member="ExpandedOrders" ThisKey="id" OtherKey="customer_id" Type="ExpandedOrders" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Line" Member="Order_Lines">
    <Type Name="Order_Line">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ship_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Product_Order_Line" Member="Product" ThisKey="product_id" OtherKey="id" Type="Product" IsForeignKey="true" />
      <Association Name="Order_Order_Line" Member="Order" ThisKey="order_id" OtherKey="id" Type="Order" IsForeignKey="true" />
      <Association Name="ExpandedOrders_Order_Line" Member="ExpandedOrders" ThisKey="order_id" OtherKey="id" Type="ExpandedOrders" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customer_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="credit_limit" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="discount" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="in_stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item_ship_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsWithPending" Member="ProductsWithPendings">
    <Type Name="ProductsWithPending">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="inventory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="Expr1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="discount" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="shipping_address_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Order_Line" Member="Order_Lines" ThisKey="id" OtherKey="order_id" Type="Order_Line" />
      <Association Name="Address_Order" Member="Address" ThisKey="shipping_address_id" OtherKey="id" Type="Address" IsForeignKey="true" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="customer_id" OtherKey="id" Type="Customer" IsForeignKey="true" />
      <Association Name="ExpandedOrders_Order" Member="ExpandedOrders" ThisKey="id" OtherKey="id" Type="ExpandedOrders" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderExpanded" Member="ExpandedOrders">
    <Type Name="ExpandedOrders">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="credit_limit" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="order_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="subtotal" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="discount" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Association Name="ExpandedOrders_Order" Member="Orders" ThisKey="id" OtherKey="id" Type="Order" Cardinality="One" />
      <Association Name="ExpandedOrders_Order_Line" Member="Order_Lines" ThisKey="id" OtherKey="order_id" Type="Order_Line" />
      <Association Name="ExpandedOrders_Customer" Member="Customers" ThisKey="customer_id" OtherKey="id" Type="Customer" />
    </Type>
  </Table>
</Database>