'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property id As Integer
    Public Property street As String
    Public Property city As String
    Public Property province As String
    Public Property postal_code As String
    Public Property type As Boolean
    Public Property customer_id As Nullable(Of Integer)

    Public Overridable Property Customer As Customer
    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)
    Public Overridable Property Customers1 As ICollection(Of Customer) = New HashSet(Of Customer)

End Class
