'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property id As Integer
    Public Property name As String
    Public Property email As String
    Public Property phone As String
    Public Property credit_limit As Decimal

    Public Overridable Property Addresses As ICollection(Of Address) = New HashSet(Of Address)
    Public Overridable Property Orders As ICollection(Of Order) = New HashSet(Of Order)

End Class
