'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order_Line
    Public Property id As Integer
    Public Property order_id As Integer
    Public Property product_id As Integer
    Public Property quantity As Integer
    Public Property ship_date As Nullable(Of Date)

    Public Overridable Property Order As Order
    Public Overridable Property Product As Product

End Class
