'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property id As Integer
    Public Property order_date As Date
    Public Property discount As Decimal
    Public Property customer_id As Integer

    Public Overridable Property Customer As Customer
    Public Overridable Property Order_Line As ICollection(Of Order_Line) = New HashSet(Of Order_Line)

End Class
