'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property id As Integer
    Public Property description As String
    Public Property price As Decimal
    Public Property inventory As Integer
    Public Property active As Boolean

    Public Overridable Property Order_Line As ICollection(Of Order_Line) = New HashSet(Of Order_Line)

End Class
